# Generated by Django 3.2.5 on 2021-08-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interconceptapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
            ],
        ),
    ]
