# Generated by Django 3.2.5 on 2021-08-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interconceptapp', '0002_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='linkedn_link',
            field=models.URLField(default=True, max_length=250),
        ),
        migrations.AddField(
            model_name='management',
            name='title',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
    ]
