# Generated by Django 3.2.5 on 2021-09-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interconceptapp', '0003_auto_20210806_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
